version: 1.0.0.{build}
os: Visual Studio 2019
environment:
  ASPNETCORE_ENVIRONMENT: appveyor
  COVERALLS_REPO_TOKEN:
    secure: fLecyAIGbJk7YBtO8UJ1g/7nSawvJs0EoBR9ckNjyMsoHTuXWxqb26tkGCkzeS66

init:
  - git config --global core.autocrlf input

install:
  - ps: Import-Module "$env:ProgramFiles\Azure Cosmos DB Emulator\PSModules\Microsoft.Azure.CosmosDB.Emulator"
  - ps: Start-CosmosDbEmulator
  - dotnet tool install --global coveralls.net

dotnet_csproj:
  patch: true
  file: 'build\version.props'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

configuration: Release

build_script:
  - dotnet pack Cosmos.Abstracts.sln --configuration Release --include-symbols --include-source

test_script:
  - dotnet test Cosmos.Abstracts.sln --configuration Release --collect:"XPlat Code Coverage" --settings coverlet.runsettings

after_test:
  - ps: .\coveralls.ps1

artifacts:
- path: artifacts\*.*nupkg
  name: Packages

deploy:
- provider: Environment
  name: MyGet